### ISSUE TITLE
Banna notendur (user og/eða ip)

### ISSUE THREAD

**Issue by Gunni** [polarina/deildu#11]
Gera stjórnendum kleift að banna notendanafn eða IP-Tölu frá því að nota kerfið.
- Einnig þarf að vera hægt að banna alla notendur sem notandi bauð inn (recursive?), hafa ban reason á recursive ban með prefix (Bann vegna banns á aðila sem bauð þér eða eitthverjum sem bauð þér, dæmi).
- Stjórnandi getur refrencað ákveðið report (#18) á banninu eða eitthvað álika þar sem action er ákveðið til þess að hafa history á afhverju eitthver var bannaður eða álika.

REQUIRES:
#21 - Notendakerfi

OPTIONAL:
Implementa https://github.com/Kjarni/KO3-Validate-IP

**Comment by polarina** [comment]
Það er einnig frekar miklvægt að geta bannað/allowað IP-ranges á síðunni jafn og sem eingöngu á tracker. Með því er hægt að mynda t.d. IP síu.
