### ISSUE TITLE
Setja error codes á síður

### ISSUE THREAD

**Issue by Gunni** [polarina/deildu#31]
### LOW PRIORITY

Dæmi:
Tracker: passkey rejected kemur á 3 stöðum, hvernig væri að kalla það passkey rejected(#1) og telja svo, sér númer fyrir hvert error.

Reason:
Gerir debugging MUN einfaldara.
Sérð instantly hvar í kóðanum userinn er að klessa á.
Böstar mögulega tilraunir til svindls með því að sjá report frá user sem var að fikta í passkeyinum ;D (ólíklegt)

**Comment by polarina** [comment]
Security through obscurity. Eins og er, gerir það notendum erfiðara að vita hvort sá hinn sami hafi átt eitthver framför í að vinna sér framhjá kerfinu.

En það ætti ekki einu sinni að vera hægt til að byrja með.

**Comment by Gunni** [comment]
ok np, setja random tölu á hverja villu innan ákveðins range og bara eitthver  sem hefur séð kóðann veit af og veit hvað þýðir :D
