### ISSUE TITLE
Blokka notendur

### ISSUE THREAD

**Issue by Gunni** [polarina/deildu#4]
Notendur verða að getað blokkað aðra notendur.

Dæmi:
Jói vill blokka Kalla. Jói fer á profile síðuna hjá Kalla og smellir á "Block" eða "Setja á óvinalista"

Áhrif:
Jói sér ekki innsend torrent frá Kalla, comment frá Kalla eru falin og topic búin til af Kalla sjást ekki.
EÐA allt þetta sést en er dimmed, dimmara en allt hitt ef þú skilur rétt.

REQUIRES:
#16 - Breyta prófíl
#21 - Notendakerfi

**Comment by polarina** [comment]
Hunsun verður implementað í réttindakerfinu (#13).
