### ISSUE TITLE
Endursetja auðkenni stafsetningarvilla

### ISSUE THREAD

**Issue by Gunni** [polarina/deildu#81]
> "Endursetning auðkennis mun ógilda allar torrent skrár sem þú hefur sótt, jafnvel þau sem nú þegar í gangi. Ef auðkenni er endursett, þarf að sækja aftur þá torrent skrár sem eru virk í torrent forriti þínu."

Did you spot the error?

> "Ef auðkenni er endursett, þarf að sækja aftur þá torrent skrár sem eru virk í torrent forriti þínu."

How'bout now?

> "sækja aftur þá torrent skrár"

Now?

**Comment by polarina** [comment]
Nope, can't see it.

**Comment by Gunni** [comment]
"Ef auðkenni er endursett, þarf að sækja aftur þá torrent skrár sem eru virk í torrent forriti þínu."
vs
"Ef auðkenni er endursett, þarf að sækja aftur **þær** torrent skrár sem eru **virkar** í torrent forriti þínu."
