### ISSUE TITLE
Halda innskráðum cookie

### ISSUE THREAD

**Issue by Gunni** [polarina/deildu#82]
Á login forminu vantar svona "Halda mér innskráðum" eða "Muna eftir mér" dæmi sem setur eitthvern remember key í cookie sem endist í liek mánuð.

Mín hugmynd er að nota nákvæmlega það sama og passkey...
1. user loggar sig inn venjulega (hakar ekki i save dótið)
   - Þú create'ar bara session cookie
2. user loggar sig inn og hakar i save dótið
   - Þú create'ar session cookie.
   - Þú createar remember cookie
   - það inniheldur (passkeyað) username + eitthvað encrypted dæmi idno?

Hvað fynnst þér?

**Comment by polarina** [comment]
Eða bara breyta expiery á session kökunni.

**Comment by Gunni** [comment]
eeeeeeeeeeeeeeeeeeeða það....

silly me að halda að sessions actually eyddust ef þau væru ekki notuð í ákveðinn tima...
